/** @type {import('tailwindcss').Config} */

export default {
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './app.vue',
    './error.vue',
  ],
  theme: {
    extend: {
      container: {
        center: true,
        padding: {
          DEFAULT: '12px',
          sm: '16px',
          md: '20px',
          lg: '48px',
          xl: '102px',
        },
      },
      fontFamily: {
        roboto: 'Roboto',
        manrope: 'Manrope',
        poppins: 'Poppins',
        montserrat: 'Montserrat',
        causten: ['Causten'],
        'core-sans-c': ['Core-Sans-C'],
      },
      colors: {
        'color-black': '#3C4242',
        'color-gray-50': '#F6F6F6',
        'color-gray-100': '#7F7F7F',
        'color-gray-200': '#807D7E',
        'gray-border': '#BEBCBD',
        'color-yellow': '#FBD103',
        'color-gray': '#676B80',
        purple: '#8A33FD',
        black: '#3C4242',
        'black-100': '#3C4242',
        'gray-300': '#666666',
        'gray-300-opacity-25': '#D9D9D9',
        'gray-300-opacity-80': '#666666CC',
        'gray-400': '#8A8989',
        'gray-500': '#BEBCBD',
        'gray-600': '#807D7E',
        red: '#FF0000',
        yellow: '#FDC761',
        brown: '#D67E3B',
        green: '#48BC4E',
        blue: '#345EFF',
        gray: '#EAE9EA',
        'my-way': '#3C4242',
      },
    },
  },
  plugins: [],
}
